name: History Compactor
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at Midnight
  workflow_dispatch:

jobs:
  compact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Compact JSON
        run: |
          # Use JQ to keep only the last 365 keys (days) for each service
          # and flatten arrays to a single status
          jq 'map_values(
            to_entries | 
            sort_by(.key) | 
            last(365) | 
            from_entries | 
            map_values(if type == "array" then (if . | contains(["Down"]) then "Down" else "Up" end) else . end)
          )' history.json > history_compact.json
          
          mv history_compact.json history.json

      - name: Commit
        run: |
          git config --global user.name "Yarm History Bot"
          git config --global user.email "it@yarmschool.org"
          git add history.json
          git commit -m "Weekly history compaction and cleanup" || echo "No changes to commit"
          git push
